name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js version 20.18.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0' 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' 

     
      - name: Build and Deploy
        run: |
          corepack enable pnpm
         
          pnpm install
          aws secretsmanager get-secret-value --secret-id Prod-myorbit-secret-frontend --output text --query "SecretString" --region us-east-1  > .env
          pnpm build
          
          ls -al && ls -al dist/
          
          aws s3 sync dist/ s3://$S3_BUCKET
          
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
